name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write  # Required to create releases and upload assets

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
            arch: x86_64
            ext: ""

          - os: macos-latest
            target: x86_64-apple-darwin
            platform: macos
            arch: x86_64
            ext: ""

          - os: macos-latest
            target: aarch64-apple-darwin
            platform: macos
            arch: aarch64
            ext: ""

          - os: windows-latest
            target: x86_64-pc-windows-gnu
            platform: windows
            arch: x86_64
            ext: ".exe"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p dist
          cp target/${{ matrix.target }}/release/clenv${{ matrix.ext }} dist/clenv-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/clenv-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
