name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            platform: linux
            arch: x86_64
          - target: x86_64-apple-darwin
            platform: macos
            arch: x86_64
          - target: aarch64-apple-darwin
            platform: macos
            arch: aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p dist
          cp target/${{ matrix.target }}/release/lwbuild dist/lwbuild-${{ matrix.platform }}-${{ matrix.arch }}
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/lwbuild-${{ matrix.platform }}-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
